{{- if not .Values.grafana.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.secretName" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.grafana.secretKeys.adminUserKey }}: {{ .Values.grafana.adminUser | quote }}
  {{ .Values.grafana.secretKeys.adminPasswordKey }}: {{ .Values.grafana.adminPassword | quote }}
{{- end }}