{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: jaeger
spec:
  type: {{ .Values.jaeger.service.type }}
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: jaeger
  ports:
    - name: ui
      port: {{ .Values.jaeger.service.uiPort }}
      targetPort: ui
      protocol: TCP
    - name: grpc
      port: {{ .Values.jaeger.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: otlp-grpc
      port: {{ .Values.jaeger.service.otlpGrpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
{{- end }}