{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Values.namespace.name }}
data:
  config.yaml: |
{{ .Values.otelCollector.config | indent 4 }}
{{- end }}