image:
  repository: thinklabsinternalacrdev.azurecr.io/infra/prometheus/prometheus
  tag: "v2.52.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9090

server:
  retention: 15d
  storagePath: /prometheus
  scrapeInterval: 15s
  evaluationInterval: 15s

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  storageClass: managed-csi-premium

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "8Gi"

nodeSelector:
  workload-type: general

tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "general"
    effect: "NoSchedule"

affinity: {}

podSecurityContext:
  fsGroup: 65534

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534

config:
  prometheusYml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]