{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.secretKeys.databaseKey }}: {{ .Values.postgres.database | quote }}
  {{ .Values.postgres.secretKeys.usernameKey }}: {{ .Values.postgres.username | quote }}
  {{ .Values.postgres.secretKeys.passwordKey }}: {{ .Values.postgres.password | quote }}
{{- end }}