{{- if .Values.clusterIPService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}-clusterip
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.clusterIPService.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}