replicaCount: 1

image:
  repository: thinklabsinternalacrdev.azurecr.io/infra/grafana/grafana
  tag: "11.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

grafana:
  adminUser: admin
  adminPassword: "change-me"
  existingSecret: ""
  secretKeys:
    adminUserKey: GF_SECURITY_ADMIN_USER
    adminPasswordKey: GF_SECURITY_ADMIN_PASSWORD

  env:
    GF_SERVER_ROOT_URL: "https://grafana.dev.thinklabs.ai"
    GF_SECURITY_ALLOW_EMBEDDING: "false"
    GF_USERS_ALLOW_SIGN_UP: "false"

  datasources:
    prometheusUrl: "http://prometheus-prometheus.monitoring.svc.cluster.local:9090"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  storageClass: managed-csi

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "2Gi"

nodeSelector:
  workload-type: general

tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "general"
    effect: "NoSchedule"

affinity: {}

ingress:
  enabled: false