{{- if .Values.slackWebhook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  webhook-url: {{ .Values.slackWebhook.url | quote }}
{{- end }}
