apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-consumer.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inference-consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inference-consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inference-consumer.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inference-consumer.fullname" . }}-sa
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: KAFKA_CONSUMER_GROUP
              value: {{ .Values.kafka.consumerGroup | quote }}